version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:latest
    # image: timescale/timescaledb:latest-pg14
    restart: unless-stopped
    # dont store data in a volume, we dont want to persist data between rebuilds
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  telegraf:
    # platform: linux/x86_64
    image: telegraf:1.30
    # env_file: configuration.env
    environment:
      - HOSTNAME=telegraf
      - USERNAME=crewchief
      - PASSWORD=crewchief
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - db
      - mosquitto-mqtt
    ports:
    - '8125:8125/udp'

  mosquitto-mqtt:
    # platform: linux/x86_64
    # container_name: mosquitto
    image: eclipse-mosquitto:2
    user: "0"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      # - ./mosquitto/data:/mosquitto/data
      # - ./mosquitto/logs:/mosquitto/logs
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto.passwords:/mosquitto/password/passwords

# volumes:
#   postgres-data:
