# Generated by Django 5.1a1 on 2024-06-28 06:52

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0025_alter_coach_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoundClip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("subtitle", models.TextField()),
                ("voice", models.CharField(max_length=200)),
                ("model", models.CharField(max_length=200)),
                ("audio_file", models.FileField(upload_to="sound_clips/")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
