# Generated by Django 5.1b1 on 2024-07-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0026_soundclip"),
    ]

    operations = [
        migrations.AddField(
            model_name="lap",
            name="completed",
            field=models.BooleanField(default=True),
        ),
    ]
