# Generated by Django 5.1b1 on 2024-07-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0029_session_car_session_track"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lap",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="segment",
            name="coasting_time",
            field=models.PositiveIntegerField(
                help_text="Time spent coasting in this segment",
                null=True,
                verbose_name="Coasting Time in centiseconds",
            ),
        ),
    ]
