# Generated by Django 5.1b1 on 2024-08-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0030_alter_lap_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="launch_wheel_slip_time",
            field=models.PositiveIntegerField(help_text="Duration of wheel slip during launch in centiseconds", null=True, verbose_name="Launch Wheel Slip Duration in centiseconds"),
        ),
    ]
