# Generated by Django 5.1b1 on 2024-10-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0031_segment_launch_wheel_slip_time"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="car",
            unique_together={("game", "name")},
        ),
    ]
