# Generated by Django 5.1b1 on 2024-11-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0033_alter_car_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="lap",
            name="official_time",
            field=models.FloatField(default=0),
        ),
    ]
